# Generated by Django 4.2.5 on 2023-10-03 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('subnet', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('UNALLOCATED', 'UNALLOCATED'), ('ALLOCATED', 'ALLOCATED')], max_length=40)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_updated_by', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
